### ISSUE TITLE
Worldwide support

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/ferrum#21]
- [ ] Login country selector
- [ ] Contacts upload normalize guess country
- [ ] Ad Form multi language description, short description, title

[More info](https://github.com/viktorvsk/carbo/issues/2)
