### ISSUE TITLE
Implement Share Menu

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/ferrum#8]
https://github.com/meedan/react-native-share-menu

- [ ] Share to chats (including chats filters)
- [ ] Share to Create Ad
- [ ] Share to Create Story
